# Generated by Django 3.1.12 on 2021-06-27 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empexp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='lastname',
        ),
    ]
