# Generated by Django 3.1.12 on 2021-06-29 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprefbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprefbook',
            name='remark',
        ),
    ]
